[general]

reticulum_host = "dev.reticulum.io"
statsd_host = "localhost:8125"
statsd_prefix = "discordbot."
hubs_hosts = "localhost,hubs.local"
hubs_hook = "Hubs"
shard_id = "1"
shard_count = "1"
verbose = "false"
locale = "en-US"
timezone = "America/Los_Angeles"
default_scene_url = "https://asset-bundles-prod.reticulum.io/rooms/atrium/Atrium.bundle.json"
